# Generated by Django 4.1.7 on 2023-03-31 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=12)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="", null=True)),
            ],
            options={
                "verbose_name_plural": "Departments",
            },
        ),
    ]
