# Generated by Django 4.1.7 on 2023-03-31 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "code",
                    models.CharField(
                        editable=False, max_length=12, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="", null=True)),
            ],
            options={
                "verbose_name_plural": "Departments",
            },
        ),
    ]
